[tool.poetry]
name = "ocs-rise-set"
version = "0.5.3"
description = "Routines for accurate rise/set/transit calculations"
authors = ["Eric Saunders <esaunders@lcogt.net>"]
readme = "README.md"
packages = [{include = "rise_set"}]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Topic :: Scientific/Engineering :: Astronomy",
]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
pyslalib = {git = "https://github.com/LCOGT/pyslalib.git@1671358d66a4142a7f6369c815d3f8830f8b5ac7"}
future = "^0.18.3"

[tool.poetry.group.dev.dependencies]
mock = "^5.0.1"
nose = "^1.3.7"
nosexcover = "^1.0.11"
coverage = "^7.2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

